### ISSUE TITLE
Filtres : picto + responsive

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#20]
- [x] dessiner puis changer les picto /!\ nouveaux filtres parcours et sélection à prévoir
- [x] diminuer taille des boutons/textes en responsive

**Comment by m-zoff** [comment]
**_dessiner puis changer les picto /!\ nouveaux filtres parcours et sélection à prévoir_**
<img width="679" alt="Capture d’écran 2023-01-17 à 22 06 37" src="https://user-images.githubusercontent.com/85549550/213012507-2d183021-1821-43c6-956e-342023a254c7.png">

Nouveaux pictos à télécharger 👇
[pictos filtre Map.zip](https://github.com/lardepa/lindex/files/10439375/pictos.filtre.Map.zip)


**_diminuer taille des boutons/textes en responsive_**
<img width="416" alt="Capture d’écran 2023-01-17 à 22 10 03" src="https://user-images.githubusercontent.com/85549550/213013092-17fc1d64-43f4-4672-9a5d-c2af92f52ae1.png">
Font size: 1rem
