### ISSUE TITLE
Cartes: légende, actions et attributions

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#37]
- [x] n'utilisez que titre et image pour les pop-up des mini-cartes + revoir la taille à la baisse
- [x] contour des pays de la Loire (souhaitable)
- [x] zoom button top right
- [x] new picto
- [x] picto legend
- [x] attributions escamotée sous une icône si petite version

**Comment by m-zoff** [comment]
**_n'utilisez que titre et image pour les pop-up des mini-cartes + revoir la taille à la baisse_**
<img width="366" alt="Capture d’écran 2023-01-17 à 22 22 06" src="https://user-images.githubusercontent.com/85549550/213014996-a33eada0-c287-4004-b358-5d2d2d36664e.png">

Ajouter une marge de 0.5rem sous l'image
Et appliquer la typo PP Neue Machina Bold (l'(aperçu et en Ultrabold mais ce serait mieux en bold) (à acheter ici : https://pangrampangram.com/products/neue-machina)

**Comment by m-zoff** [comment]
**_picto legend_**
<img width="697" alt="Capture d’écran 2023-01-17 à 22 32 53" src="https://user-images.githubusercontent.com/85549550/213016857-af2f0e22-cded-43c4-8182-3d46fb587f7f.png">

Picto : 18 x 18px ; espace de 0.5rem ; Texte : Neuzeit Grotesk Regular ; font size: 1rem ; Line heigth: 1.25rem
Espace entre chaque ligne : 0.5rem

**Comment by m-zoff** [comment]
<img width="1780" alt="Capture d’écran 2023-01-17 à 22 39 04" src="https://user-images.githubusercontent.com/85549550/213017955-04086918-473f-42c1-a69d-d256e723f665.png">
Passer les pictos en 18 x 18px

**Comment by lardepa** [comment]
- [ ] La prévisualisation des métadonnées dépasse du mini-cadre. Pas forcément grave mais au cas où, possible de corriger pour les faire passer sur deux lignes ?
![Capture meta qui depassent](https://user-images.githubusercontent.com/90329167/235172108-b5060ca2-98ba-4b1f-9c24-0fec125454d8.PNG)

**Comment by paulgirard** [comment]
Oui il faut corriger ça.
Deux solutions : 
- passer sur deux lignes mais ça ne va pas être très beau graphiquement
- couper le texte et ajouter une ellipse "..."

**Comment by lardepa** [comment]
Ok. La deuxième solution me semble pas mal mais mais je demande confirmation à la commission mercredi 03/05 dans le doute.

**Comment by paulgirard** [comment]
Est ce que vous pourriez me confirmer que les nouveaux picto de la carte sont ceux là ?
![Vector](https://user-images.githubusercontent.com/193478/236403827-4895ad1f-83ca-491d-be76-6777e4111c7c.svg)
![Polygon 14](https://user-images.githubusercontent.com/193478/236403830-81d75ea7-f129-465f-af82-d272425a274f.svg)
![Star 13](https://user-images.githubusercontent.com/193478/236403834-9dcb2dff-54b4-40ee-9752-169069af5d96.svg)

**Comment by lardepa** [comment]
Euh, pas à ma connaissance ? En tout cas je ne me souviens pas avoir validé ça, mais Maxime a eu une galère hier soir quand on devait se voir, il voulait ptet qu'on en parle.
Temporisons et on y reviendra

**Comment by lardepa** [comment]
> Est ce que vous pourriez me confirmer que les nouveaux picto de la carte sont ceux là ? ![Vector](https://user-images.githubusercontent.com/193478/236403827-4895ad1f-83ca-491d-be76-6777e4111c7c.svg) ![Polygon 14](https://user-images.githubusercontent.com/193478/236403830-81d75ea7-f129-465f-af82-d272425a274f.svg) ![Star 13](https://user-images.githubusercontent.com/193478/236403834-9dcb2dff-54b4-40ee-9752-169069af5d96.svg)

Euh, pas à ma connaissance ? En tout cas je ne me souviens pas avoir validé ça, mais Maxime a eu une galère hier soir quand on devait se voir, il voulait ptet qu'on en parle.
Temporisons et on y reviendra

**Comment by paulgirard** [comment]
J'ai trouvé ces picto dans un des figma mais je ne sais pas quelle est al version validée.
Ok pas de soucis je ne touche pas au picto pour le moment. Ça se trouve il ne faut rien changer en fait.

**Comment by m-zoff** [comment]
Hello, ces picots verts c’est des restes de tests que j’avais effectués de mon côté. Les bons picots sont ceux qui sont actuellement sur le site

**Comment by lardepa** [comment]
> **_n'utilisez que titre et image pour les pop-up des mini-cartes + revoir la taille à la baisse_** 

Arbitrages de la commission :
- [ ] Sur mobile : **afficher seulement le visuel de couverture + les MOE**
- [ ] Sur ordinateur : **afficher tout SAUF les distinctions et la typologie** (que l'on voit déjà par le picto)
- [ ] Pour les métadonnées trop longues qui dépassent du pop-up : **mettre une ellipse "(...)"**

Sur le sujet des distinctions :
- [ ] aujourd'hui, la prévisualisation indique "récompense" au lieu de "distinction", et c'est le seul titre de métadonnée qui s'affiche plusieurs fois lorsqu'il y a plusieurs distinction (voir photo ci-dessous)
**MAIS cela n'est surement pas grave puisque les distinctions n'apparaitront plus dans le pop-up**

![Capture1](https://github.com/lardepa/lindex/assets/90329167/2d6ecdb0-2e69-41bc-9e12-b5ac1f61bcd7)

**Comment by lardepa** [comment]
Nous avons créé une étiquette de **programme** "réhabilitation". Mais comme cette étiquette peut être apposées à des équipements autant qu'à des logements, à ce jour nous n'avons pas renseigné de **typologie** sur cette étiquette. Dans les métadonnées, il y a donc une étiquette de typologie vide qui s'affiche :

![Capture2](https://github.com/lardepa/lindex/assets/90329167/d39282bc-baba-4116-99ae-6c8aa20ca7f0)

Est-ce possible de demander au programme de ne pas afficher une étiquette si elle est vide ? Il y aura peut-être à terme d'autres étiquettes de ce genre.
_Ici aussi, pas grave pour la pop-up car la typologie ne s'affichera plus, mais l'étiquette vide s'affiche aussi dans la fiche du lieu._

**Comment by paulgirard** [comment]
- [ ] masquer les champs typologie vide

**Comment by paulgirard** [comment]
je bouge cette dernière demande dans le ticket #60 et ferme ce ticket là
