### ISSUE TITLE
Media : galerie en plein écran + PDF comme image

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#43]
Dans les galeries intégrées dans le site:
- [x] rendre les PDFs comme des images
- [x] garder l'icône PDF comme marqueur mais enlever l'action download
- [x] action une action au click sur n'importe quel média qui ouvre la galerie en plein écran 

Galerie en plein écran:
- [ ] permalink ?
- [x] changement d'image comme le carrousel sans mode auto
- [x] PDF en mode multipage
- [x] PDF avec bouton télécharger
- [x] vérifier l'intégration en mobile

**Comment by lardepa** [comment]
[ ] Crédits + gros (au moins sur PC)
[ ] arrière plan blanc des crédits un peu + opaque
