### ISSUE TITLE
Métadonnées des lieux

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#44]
- [x] ajuster les marges et les tailles
- [x] passer le bloc en bas de colonne sous le texte sans le rendre toujours visible (comportement sur mobile)

**Comment by m-zoff** [comment]
<img width="1506" alt="Capture d’écran 2023-01-17 à 22 57 33" src="https://user-images.githubusercontent.com/85549550/213021312-fef37319-ddf1-441b-a37f-6f49d7bfa5c1.png">



Les label type _Maitre d'œuvre_ etc. en 0.75rem ; les value type Eric Giudice Architecture : en 0.85rem 
On supprime le padding-bottom sur chaque ligne sauf sur la dernière+ 
5rem à la fin du texte et avant les métadonnées. 
Supprimer aussi le border top du bloc metadonnées

**Comment by m-zoff** [comment]
Il faudrait peut-être mettre les médias + la colonne de gauche dans une seule balise, histoire de tout scroller d'un coup et que les métadonnées de cale sur le bas de la page (avec un espacement mini de 5rem) ?

**Comment by m-zoff** [comment]
CHANGEMENT
Faire passer les métadonnées entre le titre et le texte.

**Comment by m-zoff** [comment]
![Page ExpeditionS](https://user-images.githubusercontent.com/85549550/217853321-bd69e084-a9c7-40de-ad7d-3a2efbbfd5d5.png)

**Comment by paulgirard** [comment]
il faudra sans doute revoir les espacements avec Max
