### ISSUE TITLE
page lieux en mode parcours/sélection

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#48]
- [x] Ajouter un mode lieux dans un contexte : ```/lieux/id?parcours=id 1```
- [x] Ajouter carte + liste comme dans l'objet du contexte (parcours ou sélection)

**Comment by lardepa** [comment]
- [ ] possibilité de changer l'ordre des lieux dans un parcours ?
![Capture parcours estuaire](https://user-images.githubusercontent.com/90329167/235168876-9a9a8739-0a34-4ebe-b9dd-2672f49ef2de.PNG)

**Comment by lardepa** [comment]
- [ ] Lorsqu'un lieu fait partie de plusieurs parcours, il y a un truc bizarre avec l'atténuation des segments de parcours : des segments restent visibles alors qu'ils n'ont pas de lien avec le lieu qu'on survole.
![capture parcours](https://user-images.githubusercontent.com/90329167/235170111-2a6abd48-2b54-417c-b178-cf201c856a41.jpg)

**Comment by paulgirard** [comment]
Pour changer l'ordre des lieux : il faut changer l'ordre dans airtable et regénérer le site. Il me semble avoir testé mais à vérifier.

Pour le survol : bien vu! 
Je pense que c'est à cause d'un lieu qui fait partie de plusieurs parcours.
À corriger.

**Comment by lardepa** [comment]
Pour l'ordre, effectivement ! j'avais pourtant essayé sans succès mais je m'avais du me planter quelque part. J'ai retenté et ça fonctionne ! Merci
