### ISSUE TITLE
Cartes sur mobile

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#49]
- [x] bouton pour ouvrir un itinéraire dans un outil de cartographie mobile
- [x] bouton pour se géolocaliser (explorer la carte)

**Comment by m-zoff** [comment]
<img width="395" alt="Capture d’écran 2023-01-17 à 23 20 56" src="https://user-images.githubusercontent.com/85549550/213025172-c12dd3bc-cd0c-4e37-abf7-c896f8c3320c.png">

**Comment by m-zoff** [comment]
Bouton **Créer un itinéraire** depuis la page des parcours + pages de chaque lieux

**Comment by paulgirard** [comment]
Note faisabilité
Pour "ma position" -> https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API
Pour navigation -> plus compliqué car dépendant de iOS ou Android

Si l'on souhaite rester indépendant des solutions de cartographie sous android on peut utiliser les Geo URI https://en.wikipedia.org/wiki/Geo_URI_scheme
Il faut vérifier la compatibilité sur iOS.
Pas d'itinéraire dans ce cas qu'un seul point peut être indiqué

Sinon les solutions proprio sont:
- google : https://developers.google.com/maps/documentation/urls/get-started?hl=fr
- iOS: https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

**Comment by lardepa** [comment]
Merci ! En effet, on laisse les solutions proprio de côté. 
- Ok pour "ma position"
- Ok pour afficher le point dans une autre appli (je suppose qu'après, l'utilisateur peut de toute façon cliquer lui-même sur le bouton itinéraire ?)

**Comment by lardepa** [comment]
Super pour ce bouton ! 
Seul bémol : si on a bien compris ça envoie le texte de l'adresse vers OSM ? Dans le cas de certaines notice dont l'adresse est un lieu-dit, OSM peut être un peu paumée (voir visuels ci-dessous. il s'agissait plutôt d'un bug venu de google map, mais d'autres lieux-dits pourraient être concernés)
**>> Possible de garder la même présentation dans la notice du lieu, mais que le bouton envoie la géolocalisation dans OSM plutôt que l'adresse ?**

![Capture1](https://github.com/lardepa/lindex/assets/90329167/6d1d7a73-bc49-468d-be6f-9960e56e2845)

![Capture2](https://github.com/lardepa/lindex/assets/90329167/83a895ec-aa1a-46cc-863c-574a7eb5c3dd)

**Comment by paulgirard** [comment]
J'envoie déjà la géolocalisation en plus de l'adresse.
Si tu dézoomes tu verras que "La mine " est juste à côté du point sur la carte montré.
Si tu cherches " la mine, 44170 Abbaretz" il trouve.

J'ai mis OSM mais on peut mettre autre chose si vous préférez. Cela dit dans ce cas précis l'adresse me semble tronquer.
Je trouve pas non plus ce nom d'adresse officielle dans la base d'adresse nationale: https://adresse.data.gouv.fr/base-adresse-nationale/44001#15.23/47.556848/-1.533343

**Comment by paulgirard** [comment]
OSM affiche une sorte de warning qui est assez maladroite et fait peur pour pas grand chose.
C'est une limitation de leur UX. Dans google map c'est mieux fait il propose des suggestions proches.

On ne peut pas mettre une priorité. Tel que c'est il affiche le point que je lui envoie et cherche l'adresse pour rempli le champs destination du formulaire de l'itinéraire. 
Je pense qu'il faut vivre avec que les adresses sont parfois pas connues. Surtout que sur Desktop j'envoie vers OSM mais sur mobile c'est n'importe quelle appli de carto du client ou Apple Map sous iOS.

Pour conclure, "plan d'eau de la mine, 44170, abbaretz" est reconnu par OSM ;)
