### ISSUE TITLE
Marges des menu

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#50]
- [ ] marge basse pour la preview des liens ?
- [ ] marge noire par défaut à revoir ?

**Comment by m-zoff** [comment]
noté

**Comment by m-zoff** [comment]
<img width="502" alt="Capture d’écran 2023-01-17 à 22 03 47" src="https://user-images.githubusercontent.com/85549550/213011928-c47b7706-0a70-4472-bc37-f70e49141925.png">

_Qui sommes-nous ?_ et _Mentions légales_ à la même Line Height et Font size que les boutons du dessus + **1.5rem en dessous de Mentions légales**. J'ai testé avec un padding bottom mais il y a peut-être mieux à faire je ne sais pas du tout :)

**Comment by m-zoff** [comment]
<img width="1016" alt="Capture d’écran 2023-02-09 à 16 43 21" src="https://user-images.githubusercontent.com/85549550/217862750-df70ec4a-2558-40d0-9c42-c828adf7de9d.png">
