### ISSUE TITLE
Home - carrousel

### ISSUE THREAD

**Issue by lardepa** [lardepa/lindex#59]
Juste quelques questions sur le carrousel :
- [x] Possibilité de garantir que le visuel qui apparait dans le carrousel fasse toujours la même hauteur ? Si non, on mettra toujours des photos du même format pour éviter le changement de hauteur.
- [x] Possibilité de garantir que la bande blanche dédiée au titre de l'article fasse toujours la même hauteur ?

**Comment by paulgirard** [comment]
Oui je peux contraindre les images à hauteur fixe en les coupant automatiquement. Mais ça demande de choisir pour toutes les images quelle partie de l'image est utilisée (le centre à priori ?).



Pour les titres, j'ai besoin de savoir comment vous souhaitez contraindre la hauteur en fonction des contenus.

une possibilité:
- on n'a toujours le même nombre d'élément à afficher quelque soit la news (titre + sous-titre) chacun sur une seule ligne
- de couper le texte avec une ellipse si il dépasse de la ligne 

On peut sinon choisir de:
-  mettre qu'un seul texte (titre) sur deux lignes 
-  de ne le couper que si il dépasse des deux lignes
-  de garder une ligne vide si le texte ne prendre qu'une ligne

**Comment by paulgirard** [comment]
@lardepa des nouvelles de ce ticket ? Vous souhaitez quelle solution ?

**Comment by lardepa** [comment]
Ah mince je pensais avoir publié les arbitrages, désolé.
- [ ] recadrer la photo au cas où, pour garantir qu'on voit toujours un 16:9
- [ ] garder titre + sous-titre s'il y en a un. Garder l'espace blanc s'il n'y a pas de sous-titre. Passer le titre sur deux lignes s'il est trop long, en faisant disparaitre le sous-titre. Si titre plus long que 2 lignes : ellipse

**Comment by lardepa** [comment]
- [ ] Possible d'affiner la détection de la taille de l'écran pour que le carrousel ne disparaisse pas sur un pc avec un petit écran ?

exemple sur HP pavillon laptop 13 (résolution 1920x1080 mais mise à l'échelle auto de 125% car écran de 12,9 pouces) :
![capture pc hp](https://github.com/lardepa/lindex/assets/90329167/6f53f66d-5f16-44e4-a060-cd8333113088)

**Comment by paulgirard** [comment]
pour le carrousel on peut le laisser visible sur de plus petits écrans en réduisant ou en masquant le titre "Une cartographie de l'architecture en Pays de la Loire."
