### ISSUE TITLE
tester et corriger le responsive

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#67]
- [x] galerie image sur mobile : l'utilisateur peut scroller

**Comment by lardepa** [comment]
Un petit élément inconfortable mais qui n'est pas à proprement parler un bug sur mobile : le petit encart avec la légende des picto sort de l'écran à l'arrivée sur le site. captures sur fairphone 4, sur firefox et chrome :
![Screenshot](https://github.com/lardepa/lindex/assets/90329167/049c5f32-8770-4a29-bb2a-026cd7ef58a7)

Et les pages glossaire et qui sommes nous ne s'affiche pas, sur firefox comme sur chrome. une page blanche apparait, et en swipant vers la gauche on voit les textes apparaitre sans pouvoir les centrer à l'écran :
![Screenshot_20240309-171618](https://github.com/lardepa/lindex/assets/90329167/b13814d6-0120-4d20-b837-9ba2916b4177)
![Screenshot_20240309-171624](https://github.com/lardepa/lindex/assets/90329167/b4b64dff-9139-4358-9e20-8d6d1af516d9)

**Comment by paulgirard** [comment]
J'ai corrigé le responsive sur les pages statiques.
En revanche pour la home et la page explore c'est lié au comportement des navigateur mobile. La barre d'adresse se cache qu'après le premier scroll. Or pas de scroll sur cette page. On peut la faire disparaître en scrollant sur le header entre le logo et le bouton de menu mais c'est vraiment évident. Je n'ai pas trouvé de solutions facilement.
