### ISSUE TITLE
Gestion des images

### ISSUE THREAD

**Issue by paulgirard** [lardepa/lindex#68]
deux problèmes:
- [ ] les images sont toutes chargées dans tous les formats dans github ce qui risque de bloquer le déploiement à cause d'un quota exceeded
- [ ] les images sont chargées systématiquement dans leur format le plus lourd ce qui n'est pas optimal

**Comment by lardepa** [comment]
- [ ] Est-ce-possible, quitte à ajouter un peu de développement, de bloquer sur les photos : soit tout le clic droit, soit seulement le téléchargement de la photo ?

_(on sait qu'une capture reste possible, ou même retrouver l'url de l'image avec F12, mais il s'agit plutôt de montrer de la bonne volonté sur la question des droits d'auteurs des photographes avec lesquels on va travailler, que de bloquer vraiment la récupération des images)_

**Comment by paulgirard** [comment]
Oui c'est possible mais c'est très mal vu de faire ça. Soit vous avez les droits soit vous ne les avez pas. Je ne souhaite pas mettre ça en place car ça cera juste pénible pour les utilisateurs sans apporter de solutions de protection.

**Comment by paulgirard** [comment]
On a décidé de vivre avec la solution sous-optimale actuelle.
