### ISSUE TITLE
Pages de sélections d'invités

### ISSUE THREAD

**Issue by lardepa** [lardepa/lindex#73]
- [x] ajouter le sous-titre (champ "sous-titre" de la table "sélection" dans le airtable)
- [x] Augmenter l'interligne entre le titre (nom de l'invité) et le sous-titre, et entre le sous-titre et le texte d'introduction
- [x] ajouter un peu de marge entre lelecteur soundcloud et le texte d'edito
- [x] Fonte : passer le texte d'introduction en Neuzeit (au lieu de PP Neue). Pour contraster l'introduction et l'édito, passer le l'intro dans une version de Neuzeit + grasse ? Ou passer le texte d'edito en light ?

![selection](https://github.com/lardepa/lindex/assets/90329167/c8ba3030-9ebf-4a54-a934-ffe077e866fc)

**Comment by paulgirard** [comment]
![image](https://github.com/lardepa/lindex/assets/193478/a4e02fef-1649-4da3-b997-101b52ffc13e)
Voici une proposition.
Le texte principal étant déjà en graisse 700 j'ai préféré descendre la graisse du texte de présentation à 500 pour le distinguer.
Cette graisse est d'ailleurs la même que le sous-titre qui réutilise le même style que le sous-titre des sélections. 
L'espacement du soundcloud est le même en haut et en bas (augmenter de 0.6rem).

Cette nouvelle version respire mieux et est cohérente avec le reste du site (sauf le text de l'intro qui est le seul cas de Grozeit en 500 et non 700).

**Comment by lardepa** [comment]
ok on valide !

**Comment by lardepa** [comment]
Le lecteur Soundcloud n'apparait ni sur chrome ni sur firefox, est-ce normal ?
![capture 3](https://github.com/lardepa/lindex/assets/90329167/c2442992-f193-4e7a-991f-026ad198cc9c)

**Comment by paulgirard** [comment]
Sur la page que tu pointes , le lecteur n'apparaît pas car l'URL soundloud pointe sur une page inconnue.
Sur cet autre invité cela fonctionne : 
![image](https://github.com/lardepa/lindex/assets/193478/6b74f629-2a63-457b-84d8-9d4618db395c)
